Repository EinStack/charts, pull requests merged in 2024-02, with the labels that each got.

#3 #1 ✨ Glide Helm Chart
  .gitignore
  Makefile
  README.md
  charts/glide/Chart.yaml
  charts/glide/README.md
  charts/glide/templates/NOTES.txt
  charts/glide/templates/_helpers.tpl
  charts/glide/templates/_metadata.tpl
  charts/glide/templates/_pod.tpl
  charts/glide/templates/configmap.yaml
  charts/glide/templates/deployment.yaml
  charts/glide/templates/hpa.yaml
  charts/glide/templates/ingress.yaml
  charts/glide/templates/pdb.yaml
  charts/glide/templates/service.yaml
  charts/glide/templates/serviceaccount.yaml
  charts/glide/templates/tests/test-connection.yaml
  charts/glide/values.yaml
Labels: enhancement

#6 #5: Remove extra pipe
  charts/glide/values.yaml
Labels: bug

#7 👷 #2 Configure GH Pages as a registry for EinStack charts
  .github/release.yaml
Labels: build
